"use client"

import { useEffect, useState } from "react"
import { makeId } from "@/lib/id"
import { storage } from "@/lib/storage"
import type { InVivoEvent, InVivoStudy, WorkspaceState } from "@/lib/types"

type Tab = "design" | "animals" | "workflow"

export default function InVivoWorkspace() {
  const [state, setState] = useState<WorkspaceState | null>(null)
  const [activeId, setActiveId] = useState("")
  const [tab, setTab] = useState<Tab>("design")
  const [eventType, setEventType] = useState<InVivoEvent["type"]>("Observation")
  const [eventValue, setEventValue] = useState("")
  const [eventUnit, setEventUnit] = useState("")
  const [eventAnimalId, setEventAnimalId] = useState("")

  const refresh = () => { const next=storage.getState(); setState(next); setActiveId(current => current && next.inVivoStudies.some(item => item.id === current) ? current : (next.inVivoStudies[0]?.id || "")) }
  useEffect(() => { refresh(); window.addEventListener(storage.eventName, refresh); return () => window.removeEventListener(storage.eventName, refresh) }, [])
  const study = state?.inVivoStudies.find(item => item.id === activeId)
  function save(next: InVivoStudy) { storage.saveInVivoStudy({ ...next, updatedAt: new Date().toISOString() }) }
  function createStudy() { const next: InVivoStudy = { id: makeId("invivo"), name: "Untitled in vivo study", species: "Mouse", status: "Planning", groups: [], animals: [], events: [], updatedAt: new Date().toISOString() }; storage.saveInVivoStudy(next); setActiveId(next.id) }
  function addGroup() { if (!study) return; save({ ...study, groups: [...study.groups, { id: makeId("group"), name: `Group ${study.groups.length + 1}`, treatment: "" }] }) }
  function addAnimal() { if (!study) return; const groupId=study.groups[0]?.id || ""; const id=`A${String(study.animals.length+1).padStart(3,"0")}`; save({ ...study, animals:[...study.animals,{ id:makeId("animal"), animalId:id, groupId, sex:"Unknown", weightG:null, status:"Planned" }] }) }
  function addEvent() { if (!study || !eventAnimalId || !eventValue.trim()) return; save({ ...study, events:[{ id:makeId("event"), animalId:eventAnimalId, type:eventType, value:eventValue.trim(), unit:eventUnit.trim(), createdAt:new Date().toISOString() }, ...study.events] }); setEventValue("") }

  return <div className="applicationWorkspace">
    <div className="applicationHero"><div><div className="sectionEyebrow">IN VIVO</div><h1>Plan cohorts and execute study actions with traceable records</h1><p>Study design, planned animals, groups, measurements, observations, samples and dosing records now have their own working application instead of pointing to Projects.</p></div><button className="primaryButton" onClick={createStudy}>+ New study</button></div>
    <div className="applicationTabs"><button className={tab === "design" ? "active" : ""} onClick={() => setTab("design")}>Study design</button><button className={tab === "animals" ? "active" : ""} onClick={() => setTab("animals")}>Animals & groups</button><button className={tab === "workflow" ? "active" : ""} onClick={() => setTab("workflow")}>Guided workflow</button></div>
    <div className="studySelector"><span>Study</span><select value={activeId} onChange={event => setActiveId(event.target.value)}><option value="">Select study</option>{state?.inVivoStudies.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div>
    {!study ? <div className="emptyState"><strong>Create an in vivo study</strong></div> : <>
      {tab === "design" && <section className="surfaceCard applicationFormCard"><div className="applicationEditorHead"><div><input className="applicationTitleInput" value={study.name} onChange={event => save({ ...study, name:event.target.value })}/><span>{study.animals.length} animals · {study.groups.length} groups</span></div><select value={study.status} onChange={event => save({ ...study, status:event.target.value as InVivoStudy["status"] })}><option>Planning</option><option>Running</option><option>Complete</option></select></div><div className="formGrid twoCol"><label><span>Species</span><input value={study.species} onChange={event => save({ ...study, species:event.target.value })}/></label><label><span>Status</span><input value={study.status} disabled/></label></div><div className="groupPlanner"><div className="cardHeader"><div><div className="sectionEyebrow">COHORTS</div><h2>Study groups</h2></div><button className="ghostButton" onClick={addGroup}>+ Add group</button></div>{study.groups.map(group => <div className="groupRow" key={group.id}><input value={group.name} onChange={event => save({ ...study, groups:study.groups.map(item => item.id===group.id?{...item,name:event.target.value}:item) })}/><input placeholder="Treatment / condition" value={group.treatment} onChange={event => save({ ...study, groups:study.groups.map(item => item.id===group.id?{...item,treatment:event.target.value}:item) })}/><button onClick={() => save({ ...study, groups:study.groups.filter(item=>item.id!==group.id), animals:study.animals.map(animal=>animal.groupId===group.id?{...animal,groupId:""}:animal) })}>×</button></div>)}</div></section>}
      {tab === "animals" && <section className="surfaceCard executionCard"><div className="cardHeader"><div><div className="sectionEyebrow">ANIMAL PLAN</div><h2>Planned and active animals</h2></div><button className="primaryButton" onClick={addAnimal}>+ Add animal</button></div><div className="animalTableHead"><span>ID</span><span>Group</span><span>Sex</span><span>Weight (g)</span><span>Status</span><span/></div>{study.animals.map(animal => <div className="animalTableRow" key={animal.id}><input value={animal.animalId} onChange={event=>save({...study,animals:study.animals.map(item=>item.id===animal.id?{...item,animalId:event.target.value}:item)})}/><select value={animal.groupId} onChange={event=>save({...study,animals:study.animals.map(item=>item.id===animal.id?{...item,groupId:event.target.value}:item)})}><option value="">Unassigned</option>{study.groups.map(group=><option key={group.id} value={group.id}>{group.name}</option>)}</select><select value={animal.sex} onChange={event=>save({...study,animals:study.animals.map(item=>item.id===animal.id?{...item,sex:event.target.value as typeof animal.sex}:item)})}><option>Unknown</option><option>Female</option><option>Male</option></select><input type="number" value={animal.weightG ?? ""} onChange={event=>save({...study,animals:study.animals.map(item=>item.id===animal.id?{...item,weightG:event.target.value===""?null:Number(event.target.value)}:item)})}/><select value={animal.status} onChange={event=>save({...study,animals:study.animals.map(item=>item.id===animal.id?{...item,status:event.target.value as typeof animal.status}:item)})}><option>Planned</option><option>Active</option><option>Complete</option><option>Deceased</option></select><button onClick={()=>save({...study,animals:study.animals.filter(item=>item.id!==animal.id),events:study.events.filter(event=>event.animalId!==animal.id)})}>×</button></div>)}</section>}
      {tab === "workflow" && <section className="surfaceCard executionCard"><div className="cardHeader"><div><div className="sectionEyebrow">GUIDED WORKFLOW</div><h2>Record study actions</h2></div></div><div className="eventComposer"><select value={eventAnimalId} onChange={event=>setEventAnimalId(event.target.value)}><option value="">Choose animal</option>{study.animals.map(animal=><option value={animal.id} key={animal.id}>{animal.animalId}</option>)}</select><select value={eventType} onChange={event=>setEventType(event.target.value as InVivoEvent["type"])}><option>Dose</option><option>Measurement</option><option>Sample</option><option>Observation</option></select><input placeholder="Value / note" value={eventValue} onChange={event=>setEventValue(event.target.value)}/><input placeholder="Unit" value={eventUnit} onChange={event=>setEventUnit(event.target.value)}/><button className="primaryButton" onClick={addEvent}>Record</button></div><div className="eventTimeline">{study.events.map(event=>{const animal=study.animals.find(item=>item.id===event.animalId);return <div key={event.id}><span>{event.type}</span><strong>{animal?.animalId || "Unknown animal"}</strong><p>{event.value}{event.unit ? ` ${event.unit}` : ""}</p><time>{new Date(event.createdAt).toLocaleString()}</time></div>})}{!study.events.length&&<div className="analysisEmpty">No study actions recorded yet.</div>}</div></section>}
    </>}
  </div>
}
